#!/usr/bin/env python3
"""Turn recorded CHIP-8 frames into pong-data.js.

Input: one frame per line, 512 hex chars = 64x32 pixels packed MSB-first.
Output: the first frame in full, then for each later frame only the pixel
indices that flipped (XOR against the previous frame), as 3 hex digits each.
"""
import sys

START, COUNT = int(sys.argv[2]), int(sys.argv[3])
frames = [bytes.fromhex(line.strip()) for line in open(sys.argv[1])][START:START + COUNT]

def bits(frame):
    return [(frame[i // 8] >> (7 - i % 8)) & 1 for i in range(64 * 32)]

deltas = []
prev = bits(frames[0])
for frame in frames[1:]:
    cur = bits(frame)
    deltas.append("".join(f"{i:03x}" for i in range(64 * 32) if cur[i] != prev[i]))
    prev = cur

with open("pong-data.js", "w") as out:
    out.write("// Generated by tools/record-pong/encode.py. Do not edit by hand.\n")
    out.write(f'const PONG_FIRST = "{frames[0].hex()}";\n')
    out.write(f'const PONG_DELTAS = "{",".join(deltas)}";\n')
